import logging
from . import devices
from . import endpoints
from . import licenses
from . import numbers
from . import workspaces
from .base import WbxcSession

log = logging.getLogger(__name__)


class WbxcSimpleClient:
    def __init__(self, access_token, base_url="https://webexapis.com/v1", verify=True):
        session = WbxcSession(access_token, base_url, verify)

        self.announcements = endpoints.Announcements(session)
        self.announcements_location = endpoints.AnnouncementsLocation(session)
        self.huntgroups = endpoints.HuntGroups(session)
        self.org_phone_numbers = endpoints.OrgPhoneNumbers(session)

        self.call_park_extensions = endpoints.CallParkExtensions(session)

        self.licenses = licenses.Licenses(session)
        self.devices = devices.Devices(session)
        self.locations = endpoints.Locations(session)
        self.location_call_settings = endpoints.LocationCallSettings(session)
        self.location_internal_dialing = endpoints.LocationInternalDialing(session)
        self.location_route_choices = endpoints.LocationRouteChoices(session)
        self.location_voicemail = endpoints.LocationVoicemail(session)
        self.location_voiceportal = endpoints.LocationVoicePortal(session)
        self.location_outgoing_permission = endpoints.LocationOutgoingPermission(session)
        self.location_outgoing_auto_transfer = endpoints.LocationOutgoingAutoTransferNumber(session)
        self.location_music_on_hold = endpoints.LocationMusicOnHold(session)
        self.location_pstn_options = endpoints.LocationPSTNConnectionOptions(session)
        self.location_pstn_connection = endpoints.LocationPSTNConnection(session)

        self.workspaces = endpoints.Workspaces(session)

        self.workspace_call_forwarding = endpoints.WorkspaceCallForwarding(session)
        self.workspace_call_waiting = endpoints.WorkspaceCallWaiting(session)
        self.workspace_caller_id = endpoints.WorkspaceCallerID(session)
        self.workspace_monitoring = endpoints.WorkspaceMonitoring(session)
        self.workspace_music_on_hold = endpoints.WorkspaceMusicOnHold(session)
        self.workspace_incoming_permission = endpoints.WorkspaceIncomingPermission(session)
        self.workspace_outgoing_permission = endpoints.WorkspaceOutgoingPermission(session)
        self.workspace_emergency_call_back = endpoints.WorkspaceEmergencyCallbackNumber(session)
        self.workspace_call_intercept = endpoints.WorkspaceCallIntercept(session)
        self.workspace_transfer_numbers = endpoints.WorkspaceTransferNumbers(session)
        self.workspace_associated_numbers = endpoints.WorkspaceAssociatedNumbers(session)
        self.workspace_available_phonenumbers = endpoints.WorkspaceAvailablePhoneNumbers(session)
        self.workspace_ecbn_available_phonenumbers = endpoints.WorkspaceECBNAvailablePhoneNumbers(session)
        self.workspace_callforward_available_phonenumbers = endpoints.WorkspaceCallForwardAvailablePhoneNumbers(session)
        self.workspace_callintercept_available_phonenumbers = endpoints.WorkspaceCallInterceptAvailablePhoneNumbers(session)
        self.workspace_anonymous_call_reject = endpoints.WorkspaceAnonymousCallReject(session)
        self.workspace_barge_in = endpoints.WorkspaceBargeIn(session)
        self.workspace_do_not_disturb = endpoints.WorkspaceDoNotDisturb(session)
        self.workspace_call_bridge = endpoints.WorkspaceCallBridge(session)
        self.workspace_compression = endpoints.WorkspaceCompression(session)
        self.workspace_voicemail = endpoints.WorkspaceVoicemail(session)
        self.workspace_busy_voicemail_greeting = endpoints.WorkspaceBusyVoicemailGreeting(session)
        self.workspace_no_answer_voicemail_greeting = endpoints.WorkspaceNoAnswerVoicemailGreeting(session)
        self.workspace_voicemail_passcode = endpoints.WorkspaceVoicemailPasscode(session)
        self.workspace_numbers = workspaces.WorkspaceNumbers(session)
        self.virtual_lines = endpoints.VirtualLines(session)
        self.virtual_line_call_recording = endpoints.VirtualLineCallRecording(session)
        self.virtual_line_directory_search = endpoints.VirtualLineDirectorySearch(session)
        self.virtual_line_emergency_call_back = endpoints.VirtualLineEmergencyCallbackNumber(session)
        self.virtual_line_caller_id = endpoints.VirtualLineCallerID(session)
        self.virtual_line_call_waiting = endpoints.VirtualLineCallWaiting(session)
        self.virtual_line_call_forwarding = endpoints.VirtualLineCallForwarding(session)
        self.virtual_line_incoming_permission = endpoints.VirtualLineIncomingPermission(session)
        self.virtual_line_outgoing_permission = endpoints.VirtualLineOutgoingPermission(session)
        self.virtual_line_intercept = endpoints.VirtualLineIntercept(session)
        self.virtual_line_agent_available_caller_ids = endpoints.VirtualLineAgentAvailableCallerIds(session)
        self.virtual_line_agent_caller_id = endpoints.VirtualLineAgentCallerId(session)
        self.virtual_line_voicemail = endpoints.VirtualLineVoicemail(session)
        self.virtual_line_busy_voicemail_greeting = endpoints.VirtualLineBusyVoicemailGreeting(session)
        self.virtual_line_no_answer_voicemail_greeting = endpoints.VirtualLineNoAnswerVoicemailGreeting(session)
        self.virtual_line_reset_voicemail_pin = endpoints.VirtualLineResetVoicemailPin(session)
        self.virtual_line_voicemail_passcode = endpoints.VirtualLineVoicemailPasscode(session)
        self.virtual_line_music_on_hold = endpoints.VirtualLineMusicOnHold(session)
        self.virtual_line_push_to_talk = endpoints.VirtualLinePushToTalk(session)
        self.virtual_line_call_bridge = endpoints.VirtualLineCallBridge(session)
        self.virtual_line_barge_in = endpoints.VirtualLineBargeIn(session)
        self.virtual_line_privacy = endpoints.VirtualLinePrivacy(session)
        self.virtual_line_faxmessage_availablenumbers = endpoints.VirtualLineFaxMessageAvailableNumbers(session)
        self.virtual_line_callforwarding_availablenumbers = endpoints.VirtualLineCallForwardingAvailableNumbers(session)
        self.virtual_line_availablenumbers = endpoints.VirtualLineAvailableNumbers(session)
        self.virtual_line_ecbn_availablenumbers = endpoints.VirtualLineECBNAvailableNumbers(session)

        self.voicemail_group = endpoints.VoicemailGroup(session)

        self.users = endpoints.Users(session)

        self.user_applications = endpoints.UserApplications(session)
        self.user_barge_in = endpoints.UserBargeIn(session)
        self.user_call_forwarding = endpoints.UserCallForwarding(session)
        self.user_call_intercept = endpoints.UserCallIntercept(session)
        self.user_call_intercept_greeting = endpoints.UserCallInterceptGreeting(session)
        self.user_call_recording = endpoints.UserCallRecording(session)
        self.user_call_waiting = endpoints.UserCallWaiting(session)
        self.user_caller_id = endpoints.UserCallerID(session)
        self.user_calling_behavior = endpoints.UserCallingBehavior(session)
        self.user_do_not_disturb = endpoints.UserDoNotDisturb(session)
        self.user_executive_assistant = endpoints.UserExecutiveAssistant(session)
        self.user_emergency_call_back = endpoints.UserEmergencyCallbackNumber(session)
        self.user_hoteling = endpoints.UserHoteling(session)
        self.user_monitoring = endpoints.UserMonitoring(session)
        self.user_music_on_hold = endpoints.UserMusicOnHold(session)
        self.user_incoming_permission = endpoints.UserIncomingPermission(session)
        self.user_outgoing_permission = endpoints.UserOutgoingPermission(session)
        self.user_phone_numbers = endpoints.UserPhoneNumbers(session)
        self.user_alternate_numbers = endpoints.UserAlternateNumbers(session)
        self.user_preferred_answer_endpoint = endpoints.UserPreferredAnswerEndpoint(session)
        self.user_privacy = endpoints.UserPrivacy(session)
        self.user_push_to_talk = endpoints.UserPushToTalk(session)
        self.user_reception = endpoints.UserReception(session)
        self.user_voicemail = endpoints.UserVoicemail(session)
        self.user_busy_voicemail_greeting = endpoints.UserBusyVoicemailGreeting(session)
        self.user_no_answer_voicemail_greeting = endpoints.UserNoAnswerVoicemailGreeting(session)
        self.user_reset_voicemail_pin = endpoints.UserResetVoicemailPin(session)
        self.user_voicemail_passcode = endpoints.UserVoicemailPasscode(session)
        self.user_agent_available_caller_ids = endpoints.UserAgentAvailableCallerIds(session)
        self.user_agent_caller_id = endpoints.UserAgentCallerId(session)
        self.user_compression = endpoints.UserCompression(session)
        self.user_call_bridge = endpoints.UserCallBridge(session)
        self.user_ms_teams = endpoints.UserMsTeams(session)
        self.user_ecbn_availablenumbers = endpoints.UserECBNAvailableNumbers(session)
        self.user_primary_availablenumbers = endpoints.UserAvailablePrimaryPhoneNumbers(session)
        self.user_secondary_availablenumbers = endpoints.UserAvailableSecondaryPhoneNumbers(session)
        self.user_fax_availablenumbers = endpoints.UserAvailableFaxPhoneNumbers(session)
        self.user_callforwarding_availablenumbers = endpoints.UserAvailableCallForwardPhoneNumbers(session)
        self.user_intercept_availablenumbers = endpoints.UserAvailableInterceptPhoneNumbers(session)
        self.numbers = numbers.LocationNumbers(session)
        self.device_members = devices.DeviceMembers(session)
        self.device_layout = devices.DeviceLayout(session)
        self.device_settings = devices.DeviceSettings(session)
